#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Dec  3 00:45:46 2018

@author: willhutwagner
"""

import sys

vcf=sys.argv[1]
chr1SNPs=sys.argv[2]


#only considers the 1st chrom.
vcfch1={}
with open(vcf) as fi:
    for line in fi:
        text=line.split()
        if text[0] =='CM000001.2':
            #vcfch1[position]=[reference nucleotide, alternative nucleotide]
            vcfch1[text[1]]=[text[3],text[4]]
            break
    for line in fi:
        text=line.split()
        if text[0]=='CM000001.2':
            vcfch1[text[1]]=[text[3],text[4]]
            

with open(chr1SNPs) as fi:
    for line in fi:
        text=line.split()
        if text[2] in vcfch1:
            if vcfch1[text[2]]==[text[3],text[4]]:
                print(text[5])
